language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - pip install coveralls
install:
  - "python bootstrap.py"
  - "./bin/buildout"
script:
  - "./bin/coverage run --source=bob.buildout ./bin/nosetests -sv"
after_success:
  - "coveralls"
